# Generated by Django 4.2.23 on 2025-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Лайки"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["created_at"], name="posts_like_created_1d3e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="posts_post_created_183a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author"], name="posts_post_author__19d68b_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["like_count"], name="posts_post_like_co_f65c2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subpost",
            index=models.Index(fields=["post"], name="posts_subpo_post_id_5c73d0_idx"),
        ),
    ]
