# Generated by Django 4.2.23 on 2025-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_favorite_options_alter_favorite_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки"},
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
