# Generated by Django 4.2.23 on 2025-08-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_favorite_options_post_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="post",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="parent_comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="post",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
